services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgres://postgres@db:5432/postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ""
      DB_HOST: db
      DB_PORT: 5432
      REDIS_HOST: redis
      DJANGO_SETTINGS_MODULE: tempoChat.settings
    command: ["./build.sh", "gunicorn", "tempoChat.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]

  db:
    image: postgres:13
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST: db

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_db:
