services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ""
      DB_HOST: db
      DB_PORT: ${DB_PORT}
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: db

  redis:
    image: redis:6

volumes:
  postgres_db:
