databases:
  - name: tempochatdb
    plan: free
    databaseName: tempodb
    user: tempoai

services:
  - type: web
    plan: free
    name: tempoChat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "python -m gunicorn tempoChat.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tempochatdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4