services:
  - type: web
    name: tempoChat
    env: docker
    repo: https://github.com/gbolly/tempoChat.git
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: "./build.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tempoChat-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
  - type: redis
    name: tempoChat-redis
    plan: free
    ipAllowList: []

databases:
  - name: tempoChat-db
    plan: free
    databaseName: tempodb
    user: tempoai
