services:
  - type: web
    name: tempoChat
    env: docker
    repo: https://github.com/gbolly/tempoChat.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_PASSWORD
        fromService:
          name: tempoChat-db
          property: connectionString
      - key: DB_PORT
        fromService:
          name: tempoChat-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
  - type: redis
    name: tempoChat-redis
    plan: free

databases:
  - name: tempoChat-db
    plan: free
    databaseName: tempodb
    user: tempoai
