services:
  - type: web
    name: tempoChat
    env: docker
    repo: https://github.com/gbolly/tempoChat.git
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          name: tempoChat-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: tempoChat-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - type: postgres
    name: tempoChat-db
    plan: free
    properties:
      databaseName: tempodb
      user: tempoai
      password:

service:
  - type: redis
    name: tempoChat-redis
    plan: free
